version: v1

labels:
  - label: "<Enhancement / Feature>"
    matcher:
      body: "(\\s|^)#### Summary\\s*Features +\".+\"\\s*(\n|$)"

  - label: "Info / User Interface"
    matcher:
      body: "(\\s|^)#### Summary\\s*Interface +\".+\"\\s*(\n|$)"

  - label: "Mods"
    matcher:
      body: "(\\s|^)#### Summary\\s*Mods +\".+\"\\s*(\n|$)"

  - label: "Game: Balance"
    matcher:
      body: "(\\s|^)#### Summary\\s*Balance +\".+\"\\s*(\n|$)"

  - label: "<Bugfix>"
    matcher:
      body: "(\\s|^)#### Summary\\s*Bugfixes +\".+\"\\s*(\n|$)"

  - label: "<Bugfix>"
    matcher:
      body: ".*((C|c)lose(s|d)?|(F|f)ix(es|ed)?|(R|r)esolve(s|d)?):?.*#([1-9][0-9]{3,8}).*"

  - label: "Code: Performance"
    matcher:
      body: "(\\s|^)#### Summary\\s*Performance +\".+\"\\s*(\n|$)"

  - label: "Code: Infrastructure / Style / Static Analysis"
    matcher:
      body: "(\\s|^)#### Summary\\s*Infrastructure +\".+\"\\s*(\n|$)"

  - label: "Code: Build"
    matcher:
      body: "(\\s|^)#### Summary\\s*Build +\".+\"\\s*(\n|$)"

  - label: "Translation"
    matcher:
      body: "(\\s|^)#### Summary\\s*I18N +\".+\"\\s*(\n|$)"

  - label: "[C++]"
    matcher:
      files:
        - "**/*.cpp"
        - "**/*.h"

  - label: "[JSON]"
    matcher:
      files:
        - "**/*.json"

  - label: "[Markdown]"
    matcher:
      files:
        - "**/*.md"

  - label: "Game: Achievements / Conducts / Scores"
    matcher:
      files:
        - "**/scores**"
        - "**/**statistics**"
        - "**/statistics**"
        - "**/**achievement**"
        - "**/achievement**"
        - "**/**conducts**"
        - "**/conducts**"

  - label: "[Python]"
    matcher:
      files:
        - "**/*.py"

  - label: "<Documentation>"
    matcher:
      files:
        - "**/*.md"
        - "doc/**"
        - "doxygen_doc/**"

  - label: "Code: Tooling"
    matcher:
      files:
        any:
          - ".github/**"
          - "utilities/**"
          - "tools/**"
        all: ["!tools/spell_checker/dictionary.txt"]

  - label: "Code: Tests"
    files:
      - "tests/**"
      - "data/mods/TEST_DATA/**"

  - label: "Character / World Generation"
    files:
      - "**/newcharacter**"
      - "**/worldfactory**"

  - label: "Code: Build"
    files:
      - "build-data/**"
      - "build-scripts/**"
      - "**/Makefile"
      - "**/CMakeLists.txt"
      - "**/*.cmake"

  - label: "Code: Infrastructure / Style / Static Analysis"
    files:
      - .astylerc
      - .clang-tidy
      - .editorconfig
      - .lgtm.yml

  - label: "Crafting / Construction / Recipes"
    files:
      - "**/**crafting**"
      - "**/crafting**"
      - "**/**recipe**"
      - "**/recipe**"
      - "**/**construction**"
      - "**/construction**"

  - label: "EOC: Effects On Condition"
    files:
      - "**/**effect_on_condition**"
      - "**/effect_on_condition**"
      - "**/**eoc**"
      - "**/eoc**"
      - "**/condition**"

  - label: "Fields / Furniture / Terrain / Traps"
    files:
      - "**/**furniture**"
      - "**/furniture**"
      - "**/**field**"
      - "**/field**"
      - "**/**terrain**"
      - "**/terrain**"
      - "**/**trap**"
      - "**/trap**"

  - label: "Items: Food / Vitamins"
    files:
      - "**/**food**"
      - "**/food**"
      - "**/**comestible**"
      - "**/comestible**"
      - "**/**comestible**/**"
      - "**/comestible**/**"

  - label: "NPC / Factions"
    files:
      - "**/**npc**"
      - "**/npc**"
      - "**/**NPC**"
      - "**/NPC**"

  - label: "Melee"
    files:
      - "**/**melee**"
      - "**/melee**"
      - "**/**techniques**"
      - "**/techniques**"

  - label: "Missions"
    files:
      - "**/**mission**"
      - "**/mission**"

  - label: "Info / User Interface"
    files:
      - "src/**ui**"
      - "**/ui/**"
      - "**/**widget**"
      - "**/widget**"
      - "**/**view**"
      - "**/view**"

  - label: "Items: Archery"
    files:
      - "**/archery**"
      - "**/crossbow**"

  - label: "Items: Armor / Clothing"
    files:
      - "**/**armor**"
      - "**/armor**"
      - "**/armor/**"

  - label: "Items: Battery / UPS"
    files:
      - "**/**battery**"
      - "**/battery**"

  - label: "Items: Containers"
    files:
      - "**/container**"
      - "**/**pocket**"
      - "**/pocket**"
      - "**/**contents**"
      - "**/contents**"

  - label: "Items: Magazines"
    files:
      - "**/**magazine**"
      - "**/magazine**"

  - label: "Appliance/Power Grid"
    files:
      - "**/**appliance**"
      - "**/appliance**"

  - label: "Monsters"
    files:
      - "**/**monster**"
      - "**/monster**"
      - "**/**monster**/**"
      - "**/monster**/**"

  - label: "Mutations / Traits / Professions/ Hobbies"
    files:
      - "**/**profession**"
      - "**/profession**"
      - "**/**mutation**"
      - "**/mutation**"
      - "data/mods/extra_mut_scen/**/*"
      - "**/hobbies**"

  - label: "Lore"
    files:
      - data/json/npcs/BG_trait_groups.json
      - data/json/npcs/Personality_trait_groups.json
      - data/json/npcs/personality_traits.json
      - "**/**Backgrounds**"
      - "**/Backgrounds**"
      - "**/**snippets**"
      - "**/snippets**"

  - label: "Limbs"
    files:
      - "**/**bodypart**"
      - "**/bodypart**"
      - "data/json/limb_scores.json"

  - label: "Spawn"
    files:
      - "**/**itemgroup**"
      - "**/itemgroup**"
      - "**/itemgroups/**"
      - "**/**monstergroup**"
      - "**/monstergroup**"
      - "**/monstergroups/**"

  - label: "Bionics"
    files:
      - "**/bionic**"
      - "**/**bionic**"

  - label: "Map / Mapgen"
    files:
      - "**/**mapgen**"
      - "**/mapgen**"
      - "**/mapgen/**"
      - "**/**palette**"
      - "**/**overmap**"
      - "**/overmap**"
      - "**/overmap/**"
      - "data/json/regional_map_settings.json"
      - "**/mapgen_palettes/**"

  - label: "Martial Arts"
    files:
      - "**/martialart**"

  - label: "Player Faction Base / Camp"
    files:
      - "**/basecamp**"
      - "**/faction_camp**"

  - label: "Items: Ammo / Guns"
    files:
      - "**/**gun**"
      - "**/gun**"
      - "**/**ammo**"
      - "**/ammo**"

  - label: "Items: Gunmod / Toolmod"
    files:
      - "**/**gunmod**"
      - "**/gunmod**"
      - "**/**toolmod**"
      - "**/toolmod**"

  - label: "SDL: Tiles / Sound"
    files:
      - "gfx/**"
      - "sound/**"

  - label: "Scenarios"
    files:
      - "**/scenario**"
      - "**/start_location**"

  - label: "Translation"
    files:
      - "lang/**"
      - "**/**translation**"
      - "**/translation**"

  - label: "Mods: Bombastic Perks"
    files:
      - data/mods/BombasticPerks/**/*

  - label: "Mods: Aftershock"
    files:
      - data/mods/Aftershock/**/*
      - data/mods/aftershock_exoplanet/**/*

  - label: "Mods: Backrooms"
    files:
      - data/mods/Backrooms/**/*

  - label: "Mods: Dark Days of the Dead"
    files:
      - data/mods/classic_zombies/**/*

  - label: "Mods: Dark Skies"
    files:
      - data/mods/Dark-Skies-Above/**/*

  - label: "Mods: Desert Region"
    files:
      - data/mods/desert_region/**/*

  - label: "Mods: DinoMod"
    files:
      - data/mods/DinoMod/**/*

  - label: "Mods: Extra Mutated Scenarios"
    files:
      - data/mods/extra_mut_scen/**/*

  - label: "Mods: Generic Guns"
    files:
      - data/mods/Generic_Guns/**/*

  - label: "Mods: MA"
    files:
      - data/mods/MA/**/*

  - label: "Mods: MMA"
    files:
      - data/mods/MMA/**/*

  - label: "Mods: Magiclysm"
    files:
      - data/mods/Magiclysm/**/*

  - label: "My Sweet Cataclysm 🍬"
    files:
      - data/mods/My_Sweet_Cataclysm/**/*

  - label: "Mods: Innawood 🌲"
    files:
      - data/mods/innawood/**/*

  - label: "Mods: No Hope"
    files:
      - data/mods/No_Hope/**/*

  - label: "Mods: Sorcerer"
    files:
      - data/mods/Sorcerer/**/*

  - label: "Mods: TropiCataclysm 🌴"
    files:
      - data/mods/TropiCataclysm/**/*

  - label: "Mods: Tamable Wildlife"
    files:
      - data/mods/Tamable_Wildlife/**/*

  - label: "Mods: Xedra Evolved"
    files:
      - data/mods/Xedra_Evolved/**/*

  - label: "Mods: Mind Over Matter"
    files:
      - data/mods/MindOverMatter/**/*

  - label: "Mods: Sky Island"
    files:
      - data/mods/Sky_Island/**/*

  - label: "Mods: Isolation Protocol ☣"
    files:
      - data/mods/Isolation-Protocol/**/*

  - label: "Mods"
    files:
      all: [ 'data/mods/**', '!data/mods/TEST_DATA/**', '!data/mods/dda/**', '!data/mods/dda_tutorial/**' ]

  - label: "Mechanics: Enchantments / Spells"
    files:
      any:
        - "**/**enchantment**"
        - "**/enchantment**"
        - "**/**spells**"
        - "**/spells**"
        - "**/Spells/**"
        - "**/**spell**"
      all: "!tools/**"

  - label: "Mechanics: Weather"
    files:
      - "**/weather**"

  - label: "Vehicles"
    files:
      - "**/**vehicle**"
      - "**/vehicle**"
      - "src/veh_**"
   
  - label: "Mods: Defense Mode"
    files:
      - "data/mods/Defense_Mode/**"

  - label: "Tutorial"
    files:
      - "data/mods/dda_tutorial/**"

  - label: "ImGui"
    files:
      - "src/third-party/imgui/**"
      - "src/third-party/imtui/**"
